training:
  batch_size: 128
  n_epochs: 500000
  n_iters: 200001
  ngpu: 1
  snapshot_freq: 5000
  algo: 'dsm'
  anneal_power: 2.0

data:
  dataset: "Swiss-Roll"
  logit_transform: False


model:
  sigma_begin: 1
  sigma_end: 0.01
  L: 10
  in_dim: 2
  encoder_hidden_layers: [16, 32]
  latent_space_dim: 64
  decoder_hidden_layers: [32, 16]
# The out dim is set to 1 internally (out_dim: 1)   


optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false
  

visualise:
  plot3d: True
  colormask: True
  plot_train_data: True
